export const homeObjOne = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Premium Bank',
  headline: 'Unlimited Transactions with zero fees',
  description:
    'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees',
  buttonLabel: 'Get started',
  imgStart: false,
  img: require('../../assets/images/svg-1.svg'),
  alt: 'Car',
  dark: true,
  primary: true,
  darkText: false,
}
export const homeObjTwo = {
  id: 'discover',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Unlimited Access',
  headline: 'Unlimited Transactions with zero fees',
  description:
    'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees',
  buttonLabel: 'Get started',
  imgStart: true,
  img: require('../../assets/images/svg-2.svg'),
  alt: 'discover',
  dark: false,
  primary: false,
  darkText: true,
}
export const homeObjTree = {
  id: 'services',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Premium Bank',
  headline: 'Unlimited Transactions with zero fees',
  description:
    'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees',
  buttonLabel: 'Get started',
  imgStart: false,
  img: require('../../assets/images/svg-3.svg'),
  alt: 'services',
  dark: true,
  primary: true,
  darkText: false,
}
export const homeObjFour = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Premium Bank',
  headline: 'Unlimited Transactions with zero fees',
  description:
    'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees',
  buttonLabel: 'Get started',
  imgStart: false,
  img: require('../../assets/images/svg-4.svg'),
  alt: 'Car',
  dark: true,
  primary: true,
  darkText: false,
}
export const homeObjFive = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Premium Bank',
  headline: 'Unlimited Transactions with zero fees',
  description:
    'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees',
  buttonLabel: 'Get started',
  imgStart: false,
  img: require('../../assets/images/svg-5.svg'),
  alt: 'Car',
  dark: true,
  primary: true,
  darkText: false,
}
export const homeObjSix = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Premium Bank',
  headline: 'Unlimited Transactions with zero fees',
  description:
    'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees',
  buttonLabel: 'Get started',
  imgStart: false,
  img: require('../../assets/images/svg-6.svg'),
  alt: 'Car',
  dark: true,
  primary: true,
  darkText: false,
}
